### ISSUE TITLE
Website - strange behavior

### ISSUE THREAD

**Issue by antjost** [onera/Cassiopee#227]
everything is ok when you scroll.
<img src="https://github.com/user-attachments/assets/4cbca3cd-6513-4efd-ae9a-ae6566ef5299" width=50% height=50%>

but when you do a search:
<img src="https://github.com/user-attachments/assets/bf2aeabd-396a-4e04-9186-f65d499c2860" width=50% height=50%>

**Comment by BconstantMMK** [comment]
Thanks for catching this bug, this should be fixed with my latest commit!
