### ISSUE TITLE
environement problem

### ISSUE THREAD

**Issue by antjost** [onera/Cassiopee#39]
when loading sh_Cassiopee_local it hangs @ pyversion="python"`python -c "import sys; print('.'.join(str(n) for n in sys.version_info[:2]))"` and I get the error 'bash: export: python: not a function'

I propose the follow bug fix that solves this issues: 

if [ "$PYTHONEXE" = "python3" ]; then
    pythonTmp() { python3 "$@"; }
    export -f pythonTmp
fi

instead of

if [ "$PYTHONEXE" = "python3" ]; then
    python() { python3 "$@"; }
    export -f python
fi

I tried and it works for loading the sourcing the sh_Cassiopee_local file.

**Comment by benoit128** [comment]
Hello @antjost ,
I think the problem with your solution si that you wont get the alias "python"=python3 after that change.
Can you try another solution :

if [ "$PYTHONEXE" = "python3" ]; then
    pyversion="python"`python3 -c "import sys; print('.'.join(str(n) for n in sys.version_info[:2]))"`
    alias python=python3
else
    pyversion="python"`python -c "import sys; print('.'.join(str(n) for n in sys.version_info[:2]))"`
fi
 instead of :
if [ "$PYTHONEXE" = "python3" ]; then
python() { python3 "$@"; }
export -f python
fi
pyversion="python"`python -c "import sys; print('.'.join(str(n) for n in sys.version_info[:2]))"`

Can you tell me if it works?
Thank you
a+

**Comment by benoit128** [comment]
Does anybody knows how to quote code correctly here?

**Comment by antjost** [comment]
Hello @benoit128,
Thank you for the quick response. 
I added the 'alias python=python3' higher up in the file. Similar to how it used to be when Cassiopee was in svn and I forgot to add it to the proposed bug fix.
The bug fix you proposed works. 
For the quote: I used \ \, as in  \\`  .

pyversion="python"\`python3 -c "import sys; print('.'.join(str(n) for n in sys.version_info[:2]))"`

**Comment by antjost** [comment]
> Does anybody knows how to quote code correctly here?

The circles option:
![image](https://github.com/onera/Cassiopee/assets/124277807/2c853b35-e5d1-416a-9b1f-95a6b9e8118a)
 lets you chose Code block and then you can chose shell. see below for the results
```shell
if [ "$PYTHONEXE" = "python3" ]; then
    pyversion="python"`python3 -c "import sys; print('.'.join(str(n) for n in sys.version_info[:2]))"`
    alias python=python3
else
    pyversion="python"`python -c "import sys; print('.'.join(str(n) for n in sys.version_info[:2]))"`
fi
```

**Comment by vincentcasseau** [comment]
```sh
alias python=python3
```
we removed the alias because it would not be defined in subshells without alias expansion.

**Comment by benoit128** [comment]
Thank you for the tips on code quote.

@Vince : we can discuss that on monday.
