### ISSUE TITLE
ValidCassiopee - Global Database - Fails

### ISSUE THREAD

**Issue by antjost** [onera/Cassiopee#40]
Hello,
I have the following errors for some of the validation with global database:

rotatePT_t3.py:
![rotatePT_t3](https://github.com/onera/Cassiopee/assets/124277807/8bfa8669-71dd-4bf0-a5fc-ad58f66631fa)
translatePT_t2.py:
![image](https://github.com/onera/Cassiopee/assets/124277807/d6796e49-8231-48bc-b26b-740ce6957838)

The other Fails are related to diff. values in the reference & in the current.
![image](https://github.com/onera/Cassiopee/assets/124277807/c10946c4-cf0e-4664-b931-eb7488363296)

I am up to date with the latest commit on 13/06/2024 & have no local modifs. to the code.
![image](https://github.com/onera/Cassiopee/assets/124277807/16d6a0c3-b494-4a0e-b7ab-23526a1a4c14)

**Comment by benoit128** [comment]
I reproduced the problem, but the test.testT seems classical and used everywhere.
I dont see why it fails except that they are new tests...
@vincentcasseau : any idea?

**Comment by vincentcasseau** [comment]
Hi Antoine,
There was a typo in the destination path when copying refs over to `stck` from `tmp_user`.
It should be fixed now. Many thanks for reporting it.

**Comment by antjost** [comment]
Ok thank you. I will re-test the validCassiopee and close the issue if it is resolved. thanks.

**Comment by antjost** [comment]
Thank you for the bug fix.
