### ISSUE TITLE
Non-regression test: Wind tunnel outlet pressure control

### ISSUE THREAD

**Issue by antjost** [onera/Cassiopee#53]
Add a non-regression test for the wind tunnel outlet pressure control capabilities.

**Comment by vincentcasseau** [comment]
Please consider merging some of these Issues (#48, #49, #50, #53) in the future under e.g. _Non-regression testing: add missing tests_
You can create a task list as follows:
- [x] Add test case for Feature 1
- [ ] Add test case for Feature 2
- [x] Add test case for Feature 3

**Comment by antjost** [comment]
Merged into #54
