### ISSUE TITLE
Comments in Cassiopee - Language

### ISSUE THREAD

**Issue by antjost** [onera/Cassiopee#58]
Hello, 
Given that Cassiopee is now 100% open-source and on github, therefore accessible to to whomever from wherever, I have a question on the language of new comments in the code. Should be stick with some in English and some in French or should we try to have all new comments be in English and thereby be consistent with the tutorials and user manual?
Cheers

**Comment by benoit128** [comment]
Hello,
My opinion is that it is better to keep a mix of french and english depending of the coder preference.
The most important is that comments are simple and clear.
a+

**Comment by antjost** [comment]
Ok, fair enough.
