### ISSUE TITLE
New main function names for IBMs

### ISSUE THREAD

**Issue by BconstantMMK** [onera/Cassiopee#92]
Hello there, 

I would like to change X_IBM.prepareIBMDataPara() to X_IBM.prepareIBMData() in Connector.IBM, add an alias prepareIBMDataPara = prepareIBMData and keep the old sequential X_IBM.prepareIBMData() as X_IBM.prepareIBMData_legacy(). I would like to do the same operation for G_IBM.generateIBMMeshPara() in Generator.IBM !

In the same spirit, I would like to create (and document) a postIBM main function in Post.IBM that would encapsulate several macro functions, such as _computeSkinVariables, computeAerodynamicLoads, and computeAerodynamicCoefficients.

a+

**Comment by benoit128** [comment]
Salut Benjamin,

Je suis ok pour ces changements de nom dans Connector et Generator.
OK aussi pour PostIBM.
a+
